import { updateSiteContentAction } from "@/app/admin/(panel)/actions";
import { AdminHeader } from "@/components/admin/AdminHeader";
import { AnnouncementCreateForm, AnnouncementEditForm } from "@/components/admin/EntityEditors";
import { getAnnouncements, getSiteContent } from "@/lib/repositories/content";

export default async function AdminContentPage() {
  const [content, announcements] = await Promise.all([getSiteContent(), getAnnouncements()]);
  return <><AdminHeader title="Content" description="Control homepage copy, recruitment state and announcements." /><main className="admin-content"><div className="admin-columns"><section className="admin-panel"><div className="panel-head"><h2>Homepage controls</h2></div><form action={updateSiteContentAction} className="content-form"><label>Hero headline<input name="heroHeadline" required defaultValue={content.heroHeadline} /></label><label>Hero description<textarea name="heroDescription" required defaultValue={content.heroDescription} /></label><label>Recruitment text<textarea name="recruitmentText" required defaultValue={content.recruitmentText} /></label><label>Current academic year<input name="currentAcademicYear" required pattern="\d{4}-\d{2}" defaultValue={content.currentAcademicYear} /></label><label className="inline-check"><input type="checkbox" name="recruitmentOpen" defaultChecked={content.recruitmentOpen} /> Recruitment is open</label><button className="admin-primary">Save homepage content</button></form></section><aside className="admin-panel"><div className="panel-head"><h2>Add announcement</h2></div><AnnouncementCreateForm /></aside></div><section className="admin-panel notice-editor"><div className="panel-head"><h2>Announcements</h2><span>{announcements.length} entries</span></div><div className="management-list">{announcements.map((announcement, index) => <article key={announcement.id}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{announcement.title}</strong><em>{announcement.pinned ? "Pinned · " : ""}{announcement.published ? "Published" : "Draft"}</em><p>{announcement.content}</p><AnnouncementEditForm announcement={announcement} /></div></article>)}</div></section></main></>;
}
